site:
  domain: localhost:3000
  protocol: http
amino:
  service:
    name: cantina-app
    port: 3000
redis:
  prefix: cantina-app
log:
  trace: true
  req:
    enable: true
network:
  domain: localhost
repl:
  enable: true
  options:
    prompt: "cantina-app> "
